name: Validate with hassfest

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  hassfest: # https://developers.home-assistant.io/blog/2020/04/16/hassfest
    name: Hassfest validation
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: "actions/checkout@v4.2.2"
      - name: validation
        uses: home-assistant/actions/hassfest@master

  validate-hacs: # https://github.com/hacs/action
    name: HACS validation
    runs-on: "ubuntu-latest"
    steps:
      - name: checkout
        uses: "actions/checkout@v4.2.2"
      - name: validation
        uses: "hacs/action@main"
        with:
          category: "integration"
